apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-http
  labels:
    apps: service-monitor-http
spec:
  jobLabel: service-monitor-http
  selector:
    metrics-port: http
  namespaceSelector:
    matchNames:
    - default
    - monitoring
  endpoints:
  - port: http
    interval: 30s
