apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-state-metrics
    metrics-port: http
  name: kube-state-metrics
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  selector:
    app: kube-state-metrics
