apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-state-metrics
    prometheus-metrics: web
  name: kube-state-metrics
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  selector:
    app: kube-state-metrics
