apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
    metrics-port: http
  name: node-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9100
    targetPort: metrics
    protocol: TCP
  selector:
    app: node-exporter
