apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
    metrics-port: https
  name: node-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: https
    port: 9100
    targetPort: https
  selector:
    app: node-exporter
